version: "3"

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.1.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "cbb-game-events:1:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-producer-poc:
    container_name: kafka-producer-poc
    build: .
    depends_on:
      - kafka
    hostname: "kafka-producer-poc"
    ports:
      - "8080:8080"
    environment:
      - spring.kafka.producer.bootstrap-servers=kafka:9092
    labels:
      NAME: "kafka-producer-poc"