graphql:
  spqr:
    gui:
      enabled: true

spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: cbb-game-events
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092, localhost:9093, localhost:9094

