graphql:
  spqr:
    gui:
      enabled: true

spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: cbb-game-events
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "com.flutter.streaming.kafka.serializer.protobuf.ProtobufSerializer"
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        "protobuf.add.type.headers": true
    admin:
      properties:
        bootstrap.servers: localhost:9092

